### ISSUE TITLE
How to configure this action in case the repo has a private URL?

### ISSUE THREAD

**Issue by jalexispoveda** [jonaslagoni/gh-action-dotnet-bump#20]
Hi, I tried this action in a public repo and it works like a charm, in my case the repo is not github.com, it has a private URL in a private organization. For that reason the action is not working as expected. How do I change the repo URL? I believe it's hardcoded here.

https://github.com/jonaslagoni/gh-action-dotnet-bump/blob/c0f5c67b381362a580b70a9885206af1b20ae7af/src/utils.js#L346

```
✖  fatal     remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/repo.git/'

git exited with code 128
```

in this case, `github.com` should point to a private URL.

**Comment by jonaslagoni** [comment]
Hey @jalexispoveda, Happy to accept a PR changing this behavior adding it as an option 👍😄

**Comment by jalexispoveda** [comment]
Hi @jonaslagoni I believe this fixes the issue, appreciate your feedback 😃 #21

**Comment by jalexispoveda** [comment]
Hi @jonaslagoni how do I use this release in my latest version? I am not sure if this is already deployed. Here's my action but does not seem to take the parameter into account.

```
- name:  Automated Version Bump
        uses:  joneja09/gh-action-dotnet-bump@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-part: 'Patch'
          path-to-file: 'Mango.Web/Mango.Web.csproj'
          repository-domain: 'test'
```

**Comment by jonaslagoni** [comment]
@jalexispoveda according to your image name its not this repo, should be lagoni/gh-action-dotnet-bump@main not joneja09/gh-action-dotnet-bump@main

**Comment by jalexispoveda** [comment]
@jonaslagoni  Not sure if I am doing something wrong but your action is not found in GitHub, here's the .yml I tried to run. https://github.com/jalexispoveda/net-6-micro/actions/runs/6714454256

I was able to find your action here. https://github.com/marketplace/actions/automated-version-bump-for-net-libraries this was maybe published by another person.

I couldn't find your action in the marketplace https://github.com/marketplace/actions

**Comment by jonaslagoni** [comment]
@jalexispoveda you where right, here is how I use it:

```
      - name: 'Automated Version Bump'
        uses: 'jonaslagoni/gh-action-dotnet-bump@main'
        id: version_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          skip-tag: 'true'
          skip-commit: 'true'
          path-to-file: './RustPublicAPI/RustPublicAPI.csproj'
          release-commit-message-regex: 'chore\(release\): v{{version}}'
```
